app = "keycloak-wedding"
primary_region = "lhr"

[build]
  image = "quay.io/keycloak/keycloak:26.2.4"

[env]
  KC_BOOTSTRAP_ADMIN_USERNAME = "admin"
  KC_HOSTNAME                 = "keycloak-wedding.fly.dev"
  KC_PROXY_HEADERS            = "xforwarded"
  KC_HTTP_ENABLED             = "true"
  KC_HOSTNAME_STRICT          = "false"
  KC_HEALTH_ENABLED           = "true"

[experimental]
  cmd = ["start"]

swap_size_mb = 512

[[mounts]]
  source      = "keycloak_data"
  destination = "/opt/keycloak/data"

[http_service]
  internal_port        = 8080
  force_https          = true
  auto_stop_machines   = "stop"
  auto_start_machines  = true
  min_machines_running = 1

[[vm]]
  memory   = "1gb"
  cpu_kind = "shared"
  cpus     = 1
